# Generated by Django 5.2.17 on 2026-08-12 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0004_assignment_composite_fks"),
        ("tenants", "0001_initial"),
        ("users", "0004_constraint_error_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="assignment",
            name="assignment_live_uniq",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["proposed", "accepted"])),
                fields=("mission", "user"),
                name="assignment_live_uniq",
                violation_error_message="This crew member is already assigned to this mission.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="mission",
            name="mission_dates_ordered",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="mission_dates_ordered",
                violation_error_message="End date must be on or after the start date.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="mission",
            name="mission_crew_bounds",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_crew__gte", 1), ("max_crew__gte", models.F("min_crew"))),
                name="mission_crew_bounds",
                violation_error_message="Minimum crew must be at least 1 and at most maximum crew.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="mission",
            name="mission_tenant_id_uniq",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"),
                name="mission_tenant_id_uniq",
                violation_error_message="This mission does not belong to that organisation.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="missionrequirement",
            name="requirement_proficiency_1_10",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_proficiency__gte", 1), ("min_proficiency__lte", 10)),
                name="requirement_proficiency_1_10",
                violation_error_message="Minimum proficiency must be between 1 and 10.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="missionrequirement",
            name="requirement_count_gte_1",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_count__gte", 1)),
                name="requirement_count_gte_1",
                violation_error_message="A requirement must ask for at least one crew member.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="missionrequirement",
            name="requirement_mission_skill_prof_uniq",
            constraint=models.UniqueConstraint(
                fields=("mission", "skill", "min_proficiency"),
                name="requirement_mission_skill_prof_uniq",
                violation_error_message="This skill is already required at that proficiency.",
            ),
        ),
    ]
