# Generated by Django 5.2.17 on 2026-08-12 09:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0003_tenant_composite_fks"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="crewskill",
            name="crewskill_proficiency_1_10",
            constraint=models.CheckConstraint(
                condition=models.Q(("proficiency__gte", 1), ("proficiency__lte", 10)),
                name="crewskill_proficiency_1_10",
                violation_error_message="Proficiency must be between 1 and 10.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="crewskill",
            name="crewskill_user_skill_uniq",
            constraint=models.UniqueConstraint(
                fields=("user", "skill"),
                name="crewskill_user_skill_uniq",
                violation_error_message="This skill is already listed on the profile.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="skill",
            name="skill_name_per_tenant_uniq",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="skill_name_per_tenant_uniq",
                violation_error_message="A skill with this name already exists.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="skill",
            name="skill_tenant_id_uniq",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"),
                name="skill_tenant_id_uniq",
                violation_error_message="This skill does not belong to that organisation.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="user",
            name="users_user_tenant_id_uniq",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"),
                name="users_user_tenant_id_uniq",
                violation_error_message="This user does not belong to that organisation.",
            ),
        ),
    ]
